// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSuSaiQuxTQ9y0EYZ3EuvA3kkj3jjWEDk',
    appId: '1:538852194792:web:13a5eac4d9c760ee910c5d',
    messagingSenderId: '538852194792',
    projectId: 'atelier4-h-sabt-iir5g6',
    authDomain: 'atelier4-h-sabt-iir5g6.firebaseapp.com',
    storageBucket: 'atelier4-h-sabt-iir5g6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNENFeAAsekR1aOfqzYKrJCf-u4veY6Gc',
    appId: '1:538852194792:android:aff07244c3a932a8910c5d',
    messagingSenderId: '538852194792',
    projectId: 'atelier4-h-sabt-iir5g6',
    storageBucket: 'atelier4-h-sabt-iir5g6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhV3uzGvAojYCT-dc_-X4Y9nA8kqGQ1kI',
    appId: '1:538852194792:ios:87be1e27f833a248910c5d',
    messagingSenderId: '538852194792',
    projectId: 'atelier4-h-sabt-iir5g6',
    storageBucket: 'atelier4-h-sabt-iir5g6.appspot.com',
    iosBundleId: 'com.example.atelier4HSabtIir5g6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhV3uzGvAojYCT-dc_-X4Y9nA8kqGQ1kI',
    appId: '1:538852194792:ios:c50a40c2ee962e27910c5d',
    messagingSenderId: '538852194792',
    projectId: 'atelier4-h-sabt-iir5g6',
    storageBucket: 'atelier4-h-sabt-iir5g6.appspot.com',
    iosBundleId: 'com.example.atelier4HSabtIir5g6.RunnerTests',
  );
}
